// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";

import { QuoteNFT$Type } from "./QuoteNFT";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["QuoteNFT"]: QuoteNFT$Type;
    ["contracts/QuoteNFT.sol:QuoteNFT"]: QuoteNFT$Type;
  }
}
